version: '3.8'

services:
  transcoder:
    image: livepeer/go-livepeer:0.5.29
    hostname: "transcoder"
    container_name: "transcoder"
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - lpdata:/root/.lpData
    command: '-config /root/.lpData/lptranscoder.conf'
    
volumes:
  lpdata:
    external: true
networks:
  default:
    name: livepeer
    external: true