global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

 - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
    - targets: ['node_exporter:9100']

 - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
    - targets: ['cadvisor:8080']
    
  - job_name: 'livepeer'
    metrics_path: /metrics
    static_configs:
    - targets: ['combined-orchestrator:7935']
