version: '3.8'

services:
  standalone-orchestrator:
    image: livepeer/go-livepeer:0.5.29
    hostname: "standalone-orchestrator"
    container_name: "standalone-orchestrator"
    restart: unless-stopped
    ports:
      - 8935:8935
    volumes:
      - lpdata:/root/.lpData
    command: '-config /root/.lpData/lporchestrator.conf'
    
volumes:
  lpdata:
    external: true
networks:
  default:
    name: livepeer
    external: true